import './globals.css';
import type { Metadata } from 'next';
import { Zen_Kaku_Gothic_Antique } from 'next/font/google';

const zenKakuGothicAntique = Zen_Kaku_Gothic_Antique({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export interface IRootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<IRootLayoutProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={zenKakuGothicAntique.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
